### ISSUE TITLE
2D observation spaces in gym throw error with NEAT genomes

### ISSUE THREAD

**Issue by ants224** [Talendar/nevopy#13]
Below is a simple OpenAI environment with a 2d observation space.  If you try to run this in NEvoPy the genome class throws a `ValueError: setting an array element with a sequence.`  You can duplicate this by using any of the trading environments from gym-anytrading, or with the below bare-bones environment.  I think this is related to the fact that reset is returning a n dimensional observation space but that is just a guess.

```
import gym
from gym import spaces
import numpy as np

class xCartPoleEnv(gym.Env):
  metadata = {
    'render.modes': ['human', 'rgb_array'],
    'video.frames_per_second': 50
  }

  def __init__(self):
    self.action_space = spaces.Discrete(2)
    # ==== NOTE THE 10x2 observation space here
    self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(10,2), dtype=np.float32)

 def step(self, action):
    self.state = np.zeros((10, 2))
    reward = 1.0
    done = True
    return self.state, reward, done, {}

  def reset(self):
    self.state = np.zeros((10, 2)) 
    return self.state

  def render(self, mode='human'):
    print('render')

  def close(self):
    print('close')
```

**Comment by Talendar** [comment]
Can you please post the entire code you used? It will make easier for me to understand what's going on. Also, what type of genome were you using (NEAT or fixed-topology)?

Thank you!

**Comment by ants224** [comment]
[nevopy-issue.zip](https://github.com/Talendar/nevopy/files/6166472/nevopy-issue.zip)
This is a google Colab notebook with barebones code to duplicate issue.

**Comment by Talendar** [comment]
Ok, I know what's the issue. You're trying to feed 2D inputs to NEAT genomes, which support only 1D inputs. The environment you're using probably outputs observations with recurrent networks in mind.

That said, you've two options: use fixed-topology genomes instead, which support recurrent layers; flatten the inputs before feeding them to the genomes.

Here is the fixed version of your code (flattening the inputs):
[nevopy_forex.zip](https://github.com/Talendar/nevopy/files/6167532/nevopy_forex.zip)

The best genome was able to achieve a reward of 1600 within 20 epochs.

**Comment by ants224** [comment]
Thank you for your help - I am understanding this a little better now!
